import json

stocks = [
    "20MICRONS","360ONE","3MINDIA","5PAISA","ABCAPITAL","ABFRL","ACC",
    "ADANIENT","ADANIGREEN","ADANIPORTS","ADANIPOWER","AFFLE","AJANTPHARM",
    "ALKEM","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP","APOLLOTYRE",
    "ASIANPAINT","ASTRAL","ATUL","AUBANK","AUROPHARMA","AXISBANK",
    "BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BALKRISIND","BANDHANBNK",
    "BANKBARODA","BATAINDIA","BEL","BERGEPAINT","BHARATFORG","BHARTIARTL",
    "BHEL","BIOCON","BPCL","BRITANNIA","BSOFT","CANBK","CANFINHOME",
    "CDSL","CEATLTD","CESC","CGPOWER","CHOLAFIN","CIPLA","COALINDIA",
    "COFORGE","COLPAL","CONCOR","COROMANDEL","CRISIL","CROMPTON",
    "CUMMINSIND","CYIENT","DABUR","DALBHARAT","DEEPAKNTR","DELTACORP",
    "DEVYANI","DMART","DRREDDY","EICHERMOT","EMAMILTD","ENDURANCE",
    "ESCORTS","EXIDEIND","FACT","FEDERALBNK","FIVESTAR","FLUOROCHEM",
    "FORCEMOT","FORTIS","GAIL","GICRE","GLAND","GLENMARK","GMRINFRA",
    "GODREJCP","GODREJIND","GODREJPROP","GRANULES","GRASIM","GRSE",
    "GSFC","GUJGASLTD","HAL","HAPPSTMNDS","HAVELLS","HCLTECH","HDFCAMC",
    "HDFCBANK","HDFCLIFE","HEROMOTOCO","HFCL","HINDALCO","HINDCOPPER",
    "HINDPETRO","HINDUNILVR","HUDCO","ICICIBANK","ICICIGI","ICICIPRULI",
    "IDBI","IDEA","IDFCFIRSTB","IEX","IGL","INDHOTEL","INDIAMART",
    "INDIANB","INDIGO","INDUSINDBK","INDUSTOWER","INFY","IOC","IRCTC",
    "IREDA","IRFC","ITC","JKCEMENT","JSWENERGY","JSWSTEEL","JUBLFOOD",
    "JUSTDIAL","KAJARIACER","KALYANKJIL","KOTAKBANK","LAURUSLABS",
    "LICHSGFIN","LICI","LT","LTIM","LTTS","LUPIN","M&M","M&MFIN",
    "MARICO","MARUTI","MCX","METROPOLIS","MUTHOOTFIN","NAUKRI",
    "NAZARA","NESTLEIND","NETWORK18","NHPC","NLCINDIA","NMDC","NTPC",
    "NYKAA","OBEROIRLTY","OFSS","OIL","ONGC","PAGEHIND","PATANJALI",
    "PAYTM","PERSISTENT","PETRONET","PFC","PHOENIXLTD","PIDILITIND",
    "PIIND","PNB","PNBHOUSING","POLYCAB","POONAWALLA","POWERGRID",
    "PRESTIGE","PVRINOX","RAILTEL","RBLBANK","RECLTD","RELIANCE",
    "RITES","ROSSARI","ROUTE","SAIL","SBICARD","SBILIFE","SBIN",
    "SHREECEM","SHRIRAMFIN","SIEMENS","SJVN","SRF","STARHEALTH",
    "SUNPHARMA","SUNTV","SUPREMEIND","SUZLON","SWIGGY","TANLA",
    "TATACHEM","TATACOMM","TATACONSUM","TATAELXSI","TATAMOTORS",
    "TATAPOWER","TATASTEEL","TCS","TECHM","TITAN","TORNTPHARM",
    "TORNTPOWER","TRENT","TRIDENT","TVSMOTOR","UBL","ULTRACEMCO",
    "UNIONBANK","UPL","UTIAMC","VBL","VEDL","VOLTAS","WELCORP",
    "WIPRO","YESBANK","ZEEL","ZOMATO","ZYDUSLIFE"
]

with open('frontend-new/src/nse_stocks.json', 'w') as f:
    json.dump(sorted(list(set(stocks))), f)
print(f'Saved {len(set(stocks))} stocks')
